export enum EventType {
  LOAD_FILE = 'LOAD_FILE-event',
  CHANGE_ROLE = 'CHANGE_ROLE-event',
  USER_CREATED = 'USER_CREATED-event',
  SEND_NOTIFICATION = 'SEND_NOTIFICATION-event',
  COMPETITION_PUBLISHED = 'COMPETITION_PUBLISHED-event',
  COMPETITION_STARTED = 'COMPETITION_STARETED-event',
  COMPETITION_CREATED = 'COMPETITION_CREATED-event',
  COMPETITION_DELETED = 'COMPETITION_DELETED-event',
  COMPETITION_UPDATED = 'COMPETITION_UPDATED-event',
  COMPETITION_FINISHED = 'COMPETITION_FINISHED-event',
  COMPETITION_CANCELED = 'COMPETITION_CANCELED-evnet',
  COMPETITION_ARCHIVED = 'COMPETITION_ARCHIVED-event',
}
