export enum CompetitionStatus {
  DRAFT = 'DRAFT',
  SCHEDULED = 'SCHEDULED',
  PUBLISHED = 'PUBLISHED',
  REGISTRATION = 'REGISTRATION',
  WAITING_FOR_START = 'WAITING_FOR_START',
  STARTED = 'STARTED',
  SCORING = 'SCORING',
  ARCHIVED = 'ARCHIVED',
  CANCELED = 'CANCELED',
}
