import { Command } from 'src/common/application/Command';
import { Notification } from 'src/notification/domain/entities/Notification';
import { SendNotificationEvent } from 'src/notification/domain/events/SendNotificationEvent';

interface SendTestNotificationCommandInput {
  sendToId: string;
}

const TEST_NOTIFICATION_CONTENT = `
# 🔔 Test Notification: System Ready!

Congratulations! This is an automated notification generated to verify the functionality of the **NotificationService** module.

### 🚀 What does this mean?
This confirms that your **NotificationMapper** and **Domain Entity** are working correctly:
1.  Data from the database (Schema) is successfully mapped to the domain.
2.  User relation via \`toId\` and \`toEmail\` is handled without errors.
3.  Transformation into a \`Record<string, string>\` for sockets was successful.

> **Note:** This message can be safely deleted or marked as read using the \`markAsRead\` endpoint.

---
*Automatically generated by the domain validation system.*
`.trim();

export class SendTestNotificationCommand extends Command<
  SendTestNotificationCommandInput,
  void
> {
  // eslint-disable-next-line @typescript-eslint/require-await
  async implementation(data: SendTestNotificationCommandInput): Promise<void> {
    const event = new SendNotificationEvent(
      Notification.create({
        title: 'Test notification',
        content: TEST_NOTIFICATION_CONTENT,
        from: 'System',
        targets: ['ws'],
        to: { ws: data.sendToId },
      }),
    );

    this.eventDispatcher.addEvent(event);
  }
}
